# Site wide configuration

title: "学林's Tech Blog"
description: "Collection of everythings I want to record down especially for tech"
logo: _logo.jpg # 120x120 px default image used for Twitter summary card
teaser: teaser/default.jpg# 400x250 px default teaser image used in image archive grid
locale: 
url:

default:
    -
        scope:
            type: "article"
        values:
            ads: false
            toc: false 

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Xuelin
  email: hostjorna@163.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: xuelin


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]